Add-278_first_bad_version
Amoonguses1/Leetcode pull request #22
Opened 2022-11-04 04:37 UTC by Amoonguses1

tag is binary search

2022-11-08 01:55 UTC, tkkawa requested changes

2022-11-08 01:55 UTC, tkkawa commented on 278_first_bad_version.py
> +            now = (left + right) // 2
Delete whitespaces before and space the operator in the brackets.

2022-11-13 20:58 UTC, Amoonguses1 commented
I fixed the part reviewer pointed out. I added error handling and docstring. Please check my code.
@tkkawa

2022-11-14 01:14 UTC, tkkawa approved these changes
@Amoonguses1 
LGTM

2022-11-18 15:06 UTC, merged