Add-704_binary_search.
Amoonguses1/Leetcode pull request #26
Opened 2022-11-04 13:12 UTC by Amoonguses1

binary search

2022-11-08 01:58 UTC, tkkawa requested changes

2022-11-08 01:58 UTC, tkkawa commented on 704_binary_search.py
> +# time: O(n) n is nums length
O(logn)

2022-11-08 01:58 UTC, tkkawa commented on 704_binary_search.py
> +            now = (left + right)//2
See #22 .

2022-11-13 21:09 UTC, Amoonguses1 commented
I fixed the parts reviewer pointed out. I added error handling and docstring. Please check my code.
@tkkawa

2022-11-14 01:18 UTC, tkkawa requested changes

2022-11-14 01:18 UTC, tkkawa commented on 704_binary_search.py
> +            now = (left+right)//2
Put whitespace before and after "//"

2022-11-15 01:45 UTC, Amoonguses1 commented
I have fixed to follow coding style.
@tkkawa

2022-11-15 07:01 UTC, tkkawa approved these changes
LGTM

2022-11-18 15:05 UTC, merged